app:
  host: "127.0.0.1"
  port: 5000
  debug: true
  logfile-path: app.log
  disk-usage-conf-path: disk.xml
  access-token: "@123qwe"
  postgresql:
    hostname: "localhost"
    port: 5432
    username: "postgres"
    password: "postgres"
    database: "disk_usage"